format_version: 9
pipelines:
  SampleApp:
    group: MyGroup
    materials:
      repository:
        git: https://github.com/sobbspt/gocd-sample.git
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            run-unit-test:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - "run --rm -u gradle -v '$PWD':/home/gradle/project -w /home/gradle/project gradle gradle test"